<a href="https://colab.research.google.com/github/BHAGYA938/numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# matrix using numpy


In [ ]:
import numpy as np #numerical python

#array - collection of homogeneous data.
a=np.array([1,2,3,5,4])
print(a)
print(a.ndim)        # if dim =1---> vector         ndim used to find the dimension

c=np.array([[1,2],[3,4]])
print(c)
print(c.ndim)        # if dim=2---> matrix
                     #if dim=3----> tensor


print(c.shape)      # shape is used to find the size

print(c.size)       #to find the total no of elements

[1 2 3 5 4]
1
[[1 2]
 [3 4]]
2
(2, 2)
4


In [ ]:
#forward slicing and backward slicing applicable
import numpy as np

b=np.array([1,2,3,4,5])

print(b[0:2])
print(b[5:2:-1])
print(b[3::])
print(b[1::-1])


[1 2]
[5 4]
[4 5]
[2 1]


In [ ]:
#create a 2x2 matric


import numpy as np
a=np.array([[2,3],[4,5]])
print(a)
print(a.shape)
print(a.ndim)
print(a.size)

[[2 3]
 [4 5]]
(2, 2)
2
4


In [ ]:
#create a 2x3 print the matrix,size,shape,dimension


import numpy as np
s=np.array([[1,2,3],[3,4,5]])

print(s)
print(s.ndim)
print(s.size)
print(s.shape)

[[1 2 3]
 [3 4 5]]
2
6
(2, 3)


In [ ]:
#create a 4x2 matrix


d=np.array([[1,2],[3,4],[6,7],[5,8]])
print(d)
print(d.size)
print(d.shape)
print(d.ndim)

[[1 2]
 [3 4]
 [6 7]
 [5 8]]
8
(4, 2)
2


In [ ]:
#create a 4x4

import numpy as np
d=np.array([[1,2,3,4],[3,4,8,9],[6,7,1,2],[5,8,4,5]])
print(d)
print(d.size)
print(d.shape)
print(d.ndim)
print(d[0])
print(d[:,3])      #syntax as [row,column]

print(d[1,1])
print(d[3,2:])
print(d[2:,2:])
print(d.reshape(8,2))

[[1 2 3 4]
 [3 4 8 9]
 [6 7 1 2]
 [5 8 4 5]]
16
(4, 4)
2
[1 2 3 4]
[4 9 2 5]
4
[4 5]
[[1 2]
 [4 5]]
[[1 2]
 [3 4]
 [3 4]
 [8 9]
 [6 7]
 [1 2]
 [5 8]
 [4 5]]


In [ ]:
#zero matrix

import numpy as np
a=np.zeros([3,3,3],dtype=int)   #by default float.
#dtype=complex------> a+ib
print(a)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


In [ ]:
#one matrix

import numpy as np
a=np.ones([3,3],dtype=int)
print(a)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
#create 2 2x2 matrix

import numpy as np
f=np.array([[1,2],[2,4]])
g=np.array([[3,4],[6,8]])
print(f)
print(g)

[[1 2]
 [2 4]]
[[3 4]
 [6 8]]


# matrix operations

In [ ]:
#matrix addition
print(f+g)

[[ 4  6]
 [ 8 12]]


In [ ]:
#matrix substraction

print(f-g)

[[-2 -2]
 [-4 -4]]


In [ ]:
#matrix multiplication

print(f*g)  # not matrix multiplication

print()

print(f.dot(g)) # or print(f@g)

[[ 3  8]
 [12 32]]

[[15 20]
 [30 40]]


In [ ]:
#matrix division

print(f/g)

[[0.33333333 0.5       ]
 [0.33333333 0.5       ]]


terms that starts with __ are called magic ... __add__,__sub__

In [ ]:
#full matrix---if all elements are same


import numpy as np
a=np.full([3,3],7,dtype=int)
print(a)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
#create 3x3 matix with value 9 and datatype complex


z=np.full([3,3],9,dtype=complex)
print(z)

[[9.+0.j 9.+0.j 9.+0.j]
 [9.+0.j 9.+0.j 9.+0.j]
 [9.+0.j 9.+0.j 9.+0.j]]


In [ ]:
i=np.identity(3,dtype=int)
print(i)

print()

j=np.eye(3,dtype=int)
print(j)

[[1 0 0]
 [0 1 0]
 [0 0 1]]

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
#create a 4x4 matrix



r=np.array([[1,2,3,5],[2,4,6,10],[4,8,12,20],[8,16,24,40]])

print(r)
print()

print(r.reshape(8,2))

[[ 1  2  3  5]
 [ 2  4  6 10]
 [ 4  8 12 20]
 [ 8 16 24 40]]

[[ 1  2]
 [ 3  5]
 [ 2  4]
 [ 6 10]
 [ 4  8]
 [12 20]
 [ 8 16]
 [24 40]]


In [ ]:
#arange

a=np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [ ]:
#create a 5x2 matrix using a range


b=np.arange(1,11).reshape(5,2)
print(b)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [ ]:
#create 3x3 matrix having float values

m=np.array([[1.5,2.2,3.3],[4.4,5.5,6.6],[7.7,8.8,9.9]])
print(m )

[[1.5 2.2 3.3]
 [4.4 5.5 6.6]
 [7.7 8.8 9.9]]


In [ ]:
import numpy as np
m=np.array([[1.5,2.2,3.3],[4.4,5.5,6.6],[7.7,8.8,9.9]])
print(m )
z=np.floor(m)
print(z)

print()

print(np.ceil(m))


print()


print(np.round(m))

[[1.5 2.2 3.3]
 [4.4 5.5 6.6]
 [7.7 8.8 9.9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]

[[ 2.  2.  3.]
 [ 4.  6.  7.]
 [ 8.  9. 10.]]


In [ ]:
import numpy as np
m=np.array([[1.5,2.2,3.3],[4.4,5.5,6.6],[7.7,8.8,9.9]])
print(m )

x=np.max(m,axis=1)  # axis =1 ---> row
y=np.sort(m,axis=0) # axis =0 ---> column
print(x)
print(y)

[[1.5 2.2 3.3]
 [4.4 5.5 6.6]
 [7.7 8.8 9.9]]
[3.3 6.6 9.9]
[[1.5 2.2 3.3]
 [4.4 5.5 6.6]
 [7.7 8.8 9.9]]
